#!/bin/bash

cd $(cat BUILD_DIR)
# 安装turboacc
curl -sSL https://raw.githubusercontent.com/chenmozhijin/turboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh
sed -i 's/boardinfo.model/boardinfo.system/g' feeds/luci/modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/10_system.js
sed -i 's/0.7.21/0.8.3/g' package/openwrt-clouddrive2/clouddrive2/Makefile
